# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QyEOhCuBdgmKeEk5WzeUOHS1eiSgUnMk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')
from sklearn.preprocessing import LabelEncoder

liver_df=pd.read_csv('liver.csv')
liver_df.isnull().sum()
liver_df['Albumin_and_Globulin_Ratio'].mean()
liver_df=liver_df.fillna(0.94)
X = liver_df.drop(['Gender','Dataset'], axis=1)
X.head(3)
from sklearn.model_selection import train_test_split
X=liver_df[['Age', 'Total_Bilirubin', 'Direct_Bilirubin',
       'Alkaline_Phosphotase', 'Alamine_Aminotransferase',
       'Aspartate_Aminotransferase', 'Total_Protiens', 'Albumin',
       'Albumin_and_Globulin_Ratio']]
y=liver_df['Dataset']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=123)
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=10,p=1)
KNN.fit(X_train, y_train)
knn_predicted=KNN.predict(X_test)
knn_score_train = round(KNN.score(X_train, y_train) * 100, 2)
knn_score_test = round(KNN.score(X_test, y_test) * 100, 2)
print('KNN Training Score: \n', knn_score_train)
print('KNN Test Score: \n', knn_score_test)